spring.datasource.url=jdbc:postgresql://localhost:5432/ramsai_kitchen
spring.datasource.username=ramsai
spring.datasource.password=kitchen_password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
